kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: maxkb-data
spec:
  resources:
    requests:
      storage: 200Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: hostpath
